[project]
name = "zapzap"
description = "ZapZap Backend"
requires-python = ">=3.12"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]

[tool.Ruff.lint.isort]
force-wrap-aliases = true
include_trailing_comma = true