"""add user.is_registered

Revision ID: 02721223f9bf
Revises: d4ef78611b28
Create Date: 2025-01-11 21:49:37.796583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02721223f9bf"
down_revision: Union[str, None] = "d4ef78611b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_registered", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_registered")
    # ### end Alembic commands ###
