"""frieda upgrade 3

Revision ID: 196c961f27f2
Revises: ee2bad1d85a8
Create Date: 2025-01-12 22:48:42.804818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "196c961f27f2"
down_revision: Union[str, None] = "ee2bad1d85a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tip_id", table_name="tip")
    op.create_index(op.f("ix_tip_id"), "tip", ["id"], unique=True)
    op.drop_constraint("tip_tip_receiver_fkey", "tip", type_="foreignkey")
    op.drop_column("tip", "tip_receiver")
    op.drop_index("ix_users_id", table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.add_column("tip", sa.Column("tip_receiver", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("tip_tip_receiver_fkey", "tip", "users", ["tip_receiver"], ["id"])
    op.drop_index(op.f("ix_tip_id"), table_name="tip")
    op.create_index("ix_tip_id", "tip", ["id"], unique=False)
    # ### end Alembic commands ###
