"""add tweets table

Revision ID: 1baf28fdb38b
Revises: c2714e98db98
Create Date: 2025-01-11 22:43:35.960105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1baf28fdb38b"
down_revision: Union[str, None] = "c2714e98db98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tweets_created_at"), "tweets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tweets_id"), "tweets", ["id"], unique=False)
    op.drop_column("tip", "tweet_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tweet_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_tweets_id"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_created_at"), table_name="tweets")
    op.drop_table("tweets")
    # ### end Alembic commands ###
