"""add user.is_registered nullable=false

Revision ID: 23be12d33701
Revises: 02721223f9bf
Create Date: 2025-01-11 21:56:09.532997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23be12d33701"
down_revision: Union[str, None] = "02721223f9bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_registered", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_registered", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
