"""add tweet_id FK

Revision ID: 4dc644d3abcc
Revises: 9cd8d0cd81b1
Create Date: 2025-01-11 23:35:21.672751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dc644d3abcc"
down_revision: Union[str, None] = "9cd8d0cd81b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets", "tweet_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets", "tweet_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
