"""add users.tip_recipient nullable=False

Revision ID: 4e29671dbbf5
Revises: 54ffaf269ec5
Create Date: 2025-01-11 22:19:00.656039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e29671dbbf5"
down_revision: Union[str, None] = "54ffaf269ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tip", "tip_recipient", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tip", "tip_recipient", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
