"""add users.tip_recipient

Revision ID: 54ffaf269ec5
Revises: 9ca517f4d6df
Create Date: 2025-01-11 22:18:08.460462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54ffaf269ec5"
down_revision: Union[str, None] = "9ca517f4d6df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
