"""add twitter_access_token handling

Revision ID: 558b39b4c3bf
Revises: d765e9ddb230
Create Date: 2025-01-19 15:27:45.802977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "558b39b4c3bf"
down_revision: Union[str, None] = "d765e9ddb230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_state_id", table_name="sync_state")
    op.drop_table("sync_state")
    op.add_column("users", sa.Column("twitter_access_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("twitter_refresh_token", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_column("users", "twitter_refresh_token")
    op.drop_column("users", "twitter_access_token")
    op.create_table(
        "sync_state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("last_timestamp", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="sync_state_pkey"),
    )
    op.create_index("ix_sync_state_id", "sync_state", ["id"], unique=False)
    # ### end Alembic commands ###
