"""add users.tip_sender

Revision ID: 5c8c89d1a5f3
Revises: 81f99acb7a0f
Create Date: 2025-01-11 22:16:37.773387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c8c89d1a5f3"
down_revision: Union[str, None] = "81f99acb7a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tip_sender", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tip", "users", ["tip_sender"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tip", type_="foreignkey")
    op.drop_column("tip", "tip_sender")
    # ### end Alembic commands ###
