"""tweet_id nullable=false

Revision ID: 81f99acb7a0f
Revises: 23be12d33701
Create Date: 2025-01-11 21:59:32.344270

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81f99acb7a0f"
down_revision: Union[str, None] = "23be12d33701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tip", "tweet_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tip", "tweet_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
