"""add reply_tweet_id to tip table

Revision ID: 86db4ab4f73c
Revises: 84d3e212c449
Create Date: 2025-02-20 20:21:43.543501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86db4ab4f73c'
down_revision: Union[str, None] = '84d3e212c449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tip', sa.Column('reply_tweet_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_tip_reply_tweet_id'), 'tip', ['reply_tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_reply_tweet_id'), table_name='tip')
    op.drop_column('tip', 'reply_tweet_id')
    # ### end Alembic commands ###
