"""frieda upgrade

Revision ID: 8b905ddfe52f
Revises: 6bb72154a8c9
Create Date: 2025-01-12 18:11:37.634613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b905ddfe52f"
down_revision: Union[str, None] = "6bb72154a8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tip_receiver", sa.Integer(), nullable=True))
    op.alter_column("tip", "tweet_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    op.drop_constraint("tip_tip_recipient_fkey", "tip", type_="foreignkey")
    op.create_foreign_key(None, "tip", "users", ["tip_receiver"], ["id"])
    op.drop_column("tip", "tip_recipient")
    op.add_column("tweets", sa.Column("tweet_author", sa.Integer(), nullable=True))
    op.alter_column(
        "tweets", "id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False, autoincrement=True
    )
    op.drop_index("ix_tweets_created_at", table_name="tweets")
    op.drop_index("ix_tweets_id", table_name="tweets")
    op.create_index(op.f("ix_tweets_id"), "tweets", ["id"], unique=True)
    op.create_foreign_key(None, "tweets", "users", ["tweet_author"], ["id"])
    op.drop_column("tweets", "created_at")
    op.drop_column("tweets", "tweet_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tweets", sa.Column("tweet_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column("tweets", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "tweets", type_="foreignkey")
    op.drop_index(op.f("ix_tweets_id"), table_name="tweets")
    op.create_index("ix_tweets_id", "tweets", ["id"], unique=False)
    op.create_index("ix_tweets_created_at", "tweets", ["created_at"], unique=False)
    op.alter_column(
        "tweets", "id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False, autoincrement=True
    )
    op.drop_column("tweets", "tweet_author")
    op.add_column("tip", sa.Column("tip_recipient", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "tip", type_="foreignkey")
    op.create_foreign_key("tip_tip_recipient_fkey", "tip", "users", ["tip_recipient"], ["id"])
    op.alter_column("tip", "tweet_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_column("tip", "tip_receiver")
    # ### end Alembic commands ###
