"""add users.tip_recipient

Revision ID: 9ca517f4d6df
Revises: 5c8c89d1a5f3
Create Date: 2025-01-11 22:17:44.168485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ca517f4d6df"
down_revision: Union[str, None] = "5c8c89d1a5f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tip_recipient", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tip", "users", ["tip_recipient"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tip", type_="foreignkey")
    op.drop_column("tip", "tip_recipient")
    # ### end Alembic commands ###
