"""add tweets FK

Revision ID: 9cd8d0cd81b1
Revises: 1baf28fdb38b
Create Date: 2025-01-11 23:06:59.214629

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cd8d0cd81b1"
down_revision: Union[str, None] = "1baf28fdb38b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tweet_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tip", "tweets", ["tweet_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tip", type_="foreignkey")
    op.drop_column("tip", "tweet_id")
    # ### end Alembic commands ###
