"""add twitter_access_secre

Revision ID: 9db9245deb52
Revises: 558b39b4c3bf
Create Date: 2025-01-21 19:46:51.343501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9db9245deb52"
down_revision: Union[str, None] = "558b39b4c3bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_state_id", table_name="sync_state")
    op.drop_table("sync_state")
    op.add_column("users", sa.Column("twitter_access_secret", sa.String(), nullable=True))
    op.drop_column("users", "twitter_refresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("twitter_refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("users", "twitter_access_secret")
    op.create_table(
        "sync_state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("last_timestamp", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="sync_state_pkey"),
    )
    op.create_index("ix_sync_state_id", "sync_state", ["id"], unique=False)
    # ### end Alembic commands ###
