"""initial

Revision ID: d4ef78611b28
Revises:
Create Date: 2025-01-11 21:41:33.178865

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4ef78611b28"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("tweet_id", sa.String(), nullable=True))
    op.alter_column("tip", "ln_payment_hash", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index("ix_tip_recipient_twitter_username", table_name="tip")
    op.create_index(op.f("ix_tip_created_at"), "tip", ["created_at"], unique=False)
    op.drop_constraint("tip_tipper_user_id_fkey", "tip", type_="foreignkey")
    op.drop_column("tip", "tipper_user_id")
    op.drop_column("tip", "tipper_display_name")
    op.drop_column("tip", "recipient_twitter_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip", sa.Column("recipient_twitter_username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("tip", sa.Column("tipper_display_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("tip", sa.Column("tipper_user_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("tip_tipper_user_id_fkey", "tip", "users", ["tipper_user_id"], ["id"])
    op.drop_index(op.f("ix_tip_created_at"), table_name="tip")
    op.create_index("ix_tip_recipient_twitter_username", "tip", ["recipient_twitter_username"], unique=False)
    op.alter_column("tip", "ln_payment_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("tip", "tweet_id")
    # ### end Alembic commands ###
