"""add twitter_avatar

Revision ID: d765e9ddb230
Revises: 196c961f27f2
Create Date: 2025-01-18 16:38:53.125714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d765e9ddb230"
down_revision: Union[str, None] = "196c961f27f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_state_id", table_name="sync_state")
    op.drop_table("sync_state")
    op.drop_index("ix_user_oauth_tokens_id", table_name="user_oauth_tokens")
    op.drop_table("user_oauth_tokens")
    op.drop_index("ix_tip_type_id", table_name="tip_type")
    op.drop_index("ix_tip_type_tip_type", table_name="tip_type")
    op.drop_table("tip_type")
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar_updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_updated_at")
    op.drop_column("users", "avatar_url")
    op.create_table(
        "tip_type",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("tip_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="tip_type_pkey"),
    )
    op.create_index("ix_tip_type_tip_type", "tip_type", ["tip_type"], unique=True)
    op.create_index("ix_tip_type_id", "tip_type", ["id"], unique=True)
    op.create_table(
        "user_oauth_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("oauth_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("oauth_token_secret", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="user_oauth_tokens_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="user_oauth_tokens_pkey"),
    )
    op.create_index("ix_user_oauth_tokens_id", "user_oauth_tokens", ["id"], unique=True)
    op.create_table(
        "sync_state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("last_timestamp", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="sync_state_pkey"),
    )
    op.create_index("ix_sync_state_id", "sync_state", ["id"], unique=False)
    # ### end Alembic commands ###
