"""frieda upgrade 2

Revision ID: ee2bad1d85a8
Revises: 8b905ddfe52f
Create Date: 2025-01-12 18:14:40.370939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee2bad1d85a8"
down_revision: Union[str, None] = "8b905ddfe52f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets", "tweet_author", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets", "tweet_author", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
