"""add tweet.user_id with not null

Revision ID: f399047c0c8d
Revises: 86db4ab4f73c
Create Date: 2025-03-06 18:30:08.420134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f399047c0c8d'
down_revision: Union[str, None] = '86db4ab4f73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tip', sa.Column('gif_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tip', 'gif_url')
    # ### end Alembic commands ###
